config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'pages/info'

  resources :users
  root to: redirect('/users')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :string, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @comments = @user.comments.all
    @comment = @user.comments.build
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :age, :picture, :car, :sex, :distance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_name
    = f.text_field :user_name
  .field
    = f.label :string
    = f.text_field :string
  .field
    = f.label :body
    = f.text_area :body
  = f.hidden_field :user_id
  .actions
    = f.submit

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form', comment: @comment
= link_to 'Show', @comment
|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%p#notice= notice
%h1 Comments
%table
  %thead
    %tr
      %th User name
      %th String
      %th Body
      %th User
      %th{:colspan => "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.user_name
        %td= comment.string
        %td= comment.body
        %td= comment.user_id
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New Comment
= render 'form', comment: @comment
= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong User name:
  = @comment.user_name
%p
  %strong String:
  = @comment.string
%p
  %strong Body:
  = @comment.body
%p
  %strong User:
  = @comment.user_id
= link_to 'Edit', edit_comment_path(@comment)
|
= link_to 'Back', comments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Project
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:rel =>"stylesheet", :type=>"text/css", :href =>"bootstrap.css"}
    %link{:rel =>"stylesheet", :type=>"text/css", :href =>"bootstrap-theme.css"}
  %body
    %div{:class =>"container"}

%nav{:class=>"navbar, navbar-default, navbar-fixed-top", :role=>"navigation"}
  %div{:class=>"container"}
    %div{:class=>"navbar-header"}
      %button{:type=>"button", :class=>"navbar-toggle", :"data-toggle"=>"collapse", :"data-target"=>".navbar-collapse"}
        %span{:class=>"sr-only"}Toggle navigation
        %span{:class=>"icon-bar"}
        %span{:class=>"icon-bar"}
        %span{:class=>"icon-bar"}
      %a{:class=>"navbar-brand", :href=>"/"}The Idea app
    %div{:class=>"collapse navbar-collapse"}
      %ul{:class=>"nav navbar-nav"}
        %li{:class=>"active"}
          %a{:href=>"/users"}Users
        %li
        =link_to 'New user', new_user_path

=yield

%footer
  %div{:class=>"container"} Rails Girls 2017

%script{:src=>"//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"}

app/views/pages/info.html.haml
%h1 Pages#info
%p Find me in app/views/pages/info.html.erb

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :picture
    = f.file_field :picture
  .field
    = f.label :car
    = f.text_field :car
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :distance
    = f.number_field :distance
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

-@users.in_groups_of(3) do |group|
    .row
        -group.compact.each do |user|
            .col-md-4
                =image_tag user.picture_url, width: '100%' if user.picture.present?
                %h4
                    =link_to user.name, user
                =user.distance

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p{:id=>"notice"}
    =notice

.row
    .col-md-9
        = image_tag(@user.picture_url, width: '100%') if @user.picture.present?
    .col-md-3
        %p
            %b Name:
            = @user.name
        %p
            %b distance:
            = @user.distance
        %p
            = link_to 'Edit', edit_user_path(@user)
            = link_to 'Destroy', @user, data: { confirm: 'Are you sure?' }, method: :delete
            = link_to 'Back', users_path